version: '3.6'

networks:
  jenkins-net:

volumes:
  jenkins-data:

services:
  master:
    image: seblaporte/jenkins:v1.0
    deploy:
      labels:
        - "traefik.port=9080"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:jenkins.localhost"
    ports:
      - "9080:8080"
      - "50000:50000"
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
